// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuTw0nZJoulo93pqB-mxlkf5LMhderkPQ',
    appId: '1:594263755343:web:073a4ccf1ffc856bc3b83a',
    messagingSenderId: '594263755343',
    projectId: 'clocker-d11c0',
    authDomain: 'clocker-d11c0.firebaseapp.com',
    storageBucket: 'clocker-d11c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuk_Ij4CnSB4MjmLew6RcQacRHNVrs0iY',
    appId: '1:594263755343:android:cddc0e2681f5ec34c3b83a',
    messagingSenderId: '594263755343',
    projectId: 'clocker-d11c0',
    storageBucket: 'clocker-d11c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc8mt13siocnp5Q8MhN4bGXsrUiEDJXCc',
    appId: '1:594263755343:ios:757890cf1125a71ec3b83a',
    messagingSenderId: '594263755343',
    projectId: 'clocker-d11c0',
    storageBucket: 'clocker-d11c0.appspot.com',
    iosBundleId: 'com.example.clocker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc8mt13siocnp5Q8MhN4bGXsrUiEDJXCc',
    appId: '1:594263755343:ios:757890cf1125a71ec3b83a',
    messagingSenderId: '594263755343',
    projectId: 'clocker-d11c0',
    storageBucket: 'clocker-d11c0.appspot.com',
    iosBundleId: 'com.example.clocker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuTw0nZJoulo93pqB-mxlkf5LMhderkPQ',
    appId: '1:594263755343:web:6a126057f8e4314cc3b83a',
    messagingSenderId: '594263755343',
    projectId: 'clocker-d11c0',
    authDomain: 'clocker-d11c0.firebaseapp.com',
    storageBucket: 'clocker-d11c0.appspot.com',
  );
}
